import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Card from '../components/Card'
import About from '../containers/About'
import Hero from '../containers/Hero'
import Navbar from '../containers/Navbar'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <Hero />
      <About />

      <footer className={styles.footer}>
        <p>Made by Key the Dev</p>
      </footer>
    </div>
  )
}

export default Home
