import type { NextPage } from 'next';
import Head from 'next/head';
import About from '../containers/About';
import Hero from '../containers/Hero';
import Navbar from '../containers/Navbar';
import FAQ from '../containers/FAQ';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
      </Head>

      <Navbar />
      <Hero />
      <About />
      <FAQ />
      
      <footer className={styles.footer}>
        <p>Made by Key the Dev</p>
      </footer>
    </div>
  )
}

export default Home
